# **Metrics Modules For Classification:-**

# **Confusion Matrix**

In [85]:
from sklearn.metrics import confusion_matrix

In [89]:
y_pred = ['a','a','b','b','a','b','a','a','a','a']
y_true = ['a','b','b','a','b','a','a','b','a','b']

In [94]:
print(confusion_matrix(y_true,y_pred))

[[3 2]
 [4 1]]


In [95]:
y_pred = ['a','b','c','a','b','c','a','b','c','a']
y_true = ['a','a','b','b','a','b','c','c','b','b']

In [96]:
print(confusion_matrix(y_true,y_pred))

[[1 2 0]
 [2 0 3]
 [1 1 0]]


In [97]:
y_pred = [5,8,9,9,8,5,5,9,8,5,9,8]
y_true = [9,9,8,8,5,5,9,5,8,9,8,5]

In [99]:
print(confusion_matrix(y_true, y_pred))

[[1 2 1]
 [0 1 3]
 [3 1 0]]


# **Accuracy Score**

In [100]:
from sklearn.metrics import accuracy_score

In [104]:
y_pred = [0, 2, 1, 3, 5, 3]
y_true = [0, 1, 2, 3, 5, 3]

In [107]:
'''
TP TN FP FN
TP + FP = 4

Accuracy = (TP + TN) / (TP + TN + FP + FN) = 4/6 = 0.6666666666666666
'''
print(accuracy_score(y_true, y_pred))

0.6666666666666666


In [111]:
'''
normalize = False
this return only the number of correct prediction (TP) and not the accuracy score (not deivide it by sum of all terms).
'''
print(accuracy_score(y_true, y_pred, normalize = False))

4


# **Precision "Specifity"**

In [123]:
from sklearn.metrics import precision_score

In [124]:
y_pred = ['a','b','c','a','b','c','a','b','c','a']
y_true = ['a','a','b','b','a','b','c','c','b','b']

In [127]:
print(precision_score(y_true, y_pred, average = "macro"))

0.08333333333333333


In [128]:
print(precision_score(y_true, y_pred, average = None))
'''
avg = binary, macro, weighted, samples, None "return every value"
precision = TP / (TP + FP)
'''

[0.25 0.   0.  ]


'\navg = binary, macro, weighted, samples, None "return every value"\nprecision = TP / (TP + FP)\n'

# **Recall "Sensitivity"**

In [118]:
from sklearn.metrics import recall_score

In [119]:
y_pred = ['a','b','c','a','b','c','a','b','c','a']
y_true = ['a','a','b','b','a','b','c','c','b','b']

In [129]:
print(recall_score(y_true, y_pred, average = None))

[0.33333333 0.         0.        ]


In [122]:
print(recall_score(y_true, y_pred, average = 'macro'))
'''
avg = binary, macro, weighted, samples
recall = TP / (TP + FN)
'''

0.1111111111111111


'\navg = binary, macro, weighted, samples\nrecall = TP / (TP + FN)\n'

# **F1 Score**

In [112]:
from sklearn.metrics import f1_score

In [113]:
y_pred = [0, 2, 1, 0, 0, 1]
y_true = [0, 1, 2, 0, 1, 2]

In [130]:
print(f1_score(y_true, y_pred, average = None))

[0.28571429 0.         0.        ]


In [131]:
print(f1_score(y_true, y_pred, average = 'macro'))

'''
avg = binary, macro, weighted, samples, None
f1_score = 2 * (precision * recall) / (precision + recall)
'''

0.09523809523809525


'\navg = binary, macro, weighted, samples, None\nf1_score = 2 * (precision * recall) / (precision + recall)\n'

# **Precision_Recall_Fscore_Support**

In [134]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [135]:
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])

In [136]:
print(precision_recall_fscore_support(y_true, y_pred, average = 'macro'))

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)


In [137]:
print(precision_recall_fscore_support(y_true, y_pred, average = None))

(array([0.66666667, 0.        , 0.        ]), array([1., 0., 0.]), array([0.8, 0. , 0. ]), array([2, 2, 2]))


# **Precision Recall Curve**

In [158]:
import numpy as np
from sklearn.metrics import precision_recall_curve

In [162]:
y_preddd = np.array([0, 0, 1, 1])
y_trueee = np.array([0.1, 0.4, 0.35, 0.8])

In [163]:
PrecisionValue, RecallValue, ThresholdValue = precision_recall_curve(y_preddd, y_trueee)

In [164]:
print("Precision Value:\n", PrecisionValue, "\n")
print("RecallValue:\n", RecallValue, "\n")
print("ThresholdValue:\n", ThresholdValue, "\n")

Precision Value:
 [0.5        0.66666667 0.5        1.         1.        ] 

RecallValue:
 [1.  1.  0.5 0.5 0. ] 

ThresholdValue:
 [0.1  0.35 0.4  0.8 ] 



# **Classification Report**

In [1]:
from sklearn.metrics import classification_report

In [3]:
y_true = [0, 1, 2, 2, 2, 5] # -> called quad classification (four_numbers)(0,1,2,5)
y_pred = [0, 0, 2, 2, 1, 0]

In [4]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           1       0.00      0.00      0.00         1
           2       1.00      0.67      0.80         3
           5       0.00      0.00      0.00         1

    accuracy                           0.50         6
   macro avg       0.33      0.42      0.33         6
weighted avg       0.56      0.50      0.48         6



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [5]:
y_true = ['a','d','a','g','a','d']
y_pred = ['a','a','g','g','d','g']

In [6]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           a       0.50      0.33      0.40         3
           d       0.00      0.00      0.00         2
           g       0.33      1.00      0.50         1

    accuracy                           0.33         6
   macro avg       0.28      0.44      0.30         6
weighted avg       0.31      0.33      0.28         6



# **ROC Curve**
# **"Reciever Operating Characteristic"**

In [37]:
'''
roc_curve don't take predicted values, it takes probailities values
'''
y = np.array([1 , 1 , 2 , 2])
scores = np.array([0.1 , 0.4 , 0.35, 0.8])

In [38]:
fpr, tpr, threshold_value = roc_curve(y, scores, pos_label = 2)

In [36]:
'''
tpr -> True Positive Rate -> Recall -> Sensitivity
fpr -> False Positive Rate -> Precision -> Specificity
'''
print("fpr:\n", fpr, "\n")
print("tpr:\n", tpr, "\n")
print("ThresholdValue:\n", threshold_value, "\n")

fpr:
 [0.  0.  0.5 0.5 1. ] 

tpr:
 [0.  0.5 0.5 1.  1. ] 

ThresholdValue:
 [ inf 0.8  0.4  0.35 0.1 ] 



# **AUC**
# **"Area Under Curve"**

In [39]:
from sklearn.metrics import auc
from sklearn.metrics import roc_curve

In [41]:
y = np.array([0, 0, 1, 1])
scores = np.array([0.1, 0.4, 0.35, 0.8])

In [42]:
fpr, tpr, threshold_value = roc_curve(y, scores)

In [43]:
roc_auc_score(y, scores)

0.75

In [44]:
print(auc(fpr, tpr))

0.75


# **ROC AUC Score**

In [45]:
from sklearn.metrics import roc_auc_score

In [46]:
y = np.array([0, 0, 1, 1])
scores = np.array([0.1, 0.4, 0.35, 0.8])

In [47]:
print(roc_auc_score(y, scores))

0.75


# **Zero One Loss**

In [53]:
from sklearn.metrics import zero_one_loss

In [57]:
y_pred = [1, 2, 3, 4]
y_true = [2, 2, 3, 4]

In [64]:
'''
ratio of wrong predictions
'''

print(zero_one_loss(y_true, y_pred))

0.25


In [65]:
'''
return the number of wrong predictions
'''

print(zero_one_loss(y_true, y_pred, normalize = False))

1
