# **Any Dataaa**

In [24]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [19]:
data = pd.read_csv("Salary_Data.csv")

In [40]:
data = pd.DataFrame(data)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [39]:
data.head()

0        1
0  1.1  39343.0
1  1.3  46205.0
2  1.5  37731.0
3  2.0  43525.0
4  2.2  39891.0

In [44]:
'''
Cleaning Data:-
Imputation transformer for completing missing values.
impute.SimpleImputer(missing_values = np.nan, strategy = 'mean’, fill_value = None, verbose = 0, copy = True)
strategy = "mean" , "median" , "most_frequent" , "constant"
'''

imputee = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputeeX = imputee.fit(x)
x = imputeeX.transform(x)

In [43]:
print(x)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


# **DataFile In Sklearn**

In [51]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.impute import SimpleImputer

In [52]:
dataset = load_breast_cancer()

In [53]:
X = dataset.data
y = dataset.target

In [54]:
imputee = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputeeX = imputee.fit(X)
X = imputeeX.transform(X)

In [55]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [63]:
imputeee = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputeeY = imputeee.fit(y.reshape(-1, 1)) # Reshape y to a 2D array
y = imputeeY.transform(y.reshape(-1, 1)).flatten() # Flatten the result to a 1D array

In [64]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1.
 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0.
 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0.

# **Given Data**

In [77]:
data = [[1, 2, np.nan],  # np.nan != 0
        [3, np.nan, 1],
        [np.nan, 4, 6],
        [5, 0, np.nan],
        [4, 5, 5]]

In [72]:
imp = SimpleImputer(missing_values = np.nan, strategy = 'median')
imp = imp.fit(data)
modifieddata = imp.transform(data)
print(modifieddata)

[[1.  2.  5. ]
 [3.  3.  1. ]
 [3.5 4.  6. ]
 [5.  0.  5. ]
 [4.  5.  5. ]]


In [76]:
d = [[1,2,0], [3,0,1], [5,0,0], [0,4,6], [5,0,0], [4,5,5]]
im = SimpleImputer(missing_values = 0, strategy = 'median')
im = im.fit(d)
modifiedd = im.transform(d)
print(d)

[[1, 2, 0], [3, 0, 1], [5, 0, 0], [0, 4, 6], [5, 0, 0], [4, 5, 5]]
