# **train_test_split**

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
x = np.arange(10).reshape((5, 2))

In [5]:
y = range(5)

In [6]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
y

range(0, 5)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, shuffle=True)
# test will take 1/5 of data
# shuffle means reordering the data

In [9]:
x_train

array([[8, 9],
       [4, 5],
       [0, 1],
       [6, 7]])

In [10]:
x_test

array([[2, 3]])

In [11]:
y_train

[4, 2, 0, 3]

In [12]:
y_test

[1]

# **K-Fold**

In [18]:
import numpy as np
from sklearn.model_selection import KFold

In [19]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])

In [23]:
nn = 2
kf = KFold(n_splits = nn, random_state = None, shuffle = False)

In [33]:
for train_index, test_index in kf.split(x):
    print(train_index, test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("x_train: \n", x_train, "\n")
    print("x_test : \n", x_test, "\n")
    print("y_train : \n", y_train, "\n")
    print("y_test : \n", y_test, "\n")

[2 3] [0 1]
x_train: 
 [[5 6]
 [7 8]] 

x_test : 
 [[1 2]
 [3 4]] 

y_train : 
 [33 44] 

y_test : 
 [11 22] 

[0 1] [2 3]
x_train: 
 [[1 2]
 [3 4]] 

x_test : 
 [[5 6]
 [7 8]] 

y_train : 
 [11 22] 

y_test : 
 [33 44] 

